const data = {
  code: 0,
  result: {
    standardAdList: [],
    liteAdList: [
      {
        _id: "617b8fc56bdf9700390f411f",
        gymName: "이화 제이앤에스바디플로우 ",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ccaa99cad35cddc0/2YUdxPMLRE9DV22ZxcNn4LghHJ9vJ1Cze5Tv.Big_3.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ccaa99cad35cddc0/2YC5MsVTS6WFpSrj7j6Mj54BQRMQVL1Y2SkR.Small_3.jpg",
        address: "서울 종로구 이화동",
        location: [127.00480280310884, 37.5776199560746],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: [
          "필라테스",
          "기구필라테스",
          "자이로토닉",
          "자이로키네시스",
          "스트레칭",
        ],
        program: {
          free: "️쳬형측정(5만원 상당)",
        },
        service: {
          free: "️수건 / ️공용락커",
        },
        price: {
          name: "매트 필라테스",
          count: 30,
          isLowestPrice: true,
          lowestPrice: 432000,
          originalPrice: 480000,
          period: null,
          priceType: "count",
          itemTags: ["필라테스"],
          lowestPriceRemainingCount: 5,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
      {
        _id: "66598f406a36af001d813f9d",
        gymName: "시청 피트니스온",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18fcdd79463342aa28/2Zw9JCqfv33TgjXzG2j9NCEpp6eXri6Pk3zG.Big_15.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18fcdd79463342aa28/2YBLc2P6ECeDH15A7K13xykGCCSJhkEMDqo5.Small_15.jpg",
        address: "서울 중구 무교동",
        location: [126.9796085839833, 37.56731991944422],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "골프"],
        program: {
          free: "OT 2회 무료",
        },
        service: {
          free: "사우나, 바디워시, 샴푸 제공",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 455000,
          originalPrice: 495000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 16,
        },
        review: {
          rate: 5,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
      {
        _id: "60a70f3bc70b9e003994f62b",
        gymName: "창신 클래식바디짐",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1798c9381d313d5d46/2WiS7BUjMSWrZ6EoWc42cAwCky66tG7CTsG6.Big_1.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1798c9381d313d5d46/2WNFCNJ7A3Sc4RnvT3sBEuNfARhdK4zKvoNu.Small_1.jpg",
        address: "서울 종로구 창신동",
        location: [127.01483454889022, 37.577748608011525],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복 / 수건 / ️Wi-fi / ️주차 3시간",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 260000,
          originalPrice: 270000,
          period: 6,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 50,
        },
        review: {
          rate: 4.92,
          count: 39,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
      {
        _id: "65fb96e46d09b7001d9d1fa0",
        gymName: "시청 무브짐앤무브맥스PT",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e5ec56c2a2c8a2e4/43D6ieGSQgRbwJmudqjrWKoD1VnvZDusnori.background_photo.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e5ec56c2a2c8a2e4/2WiSHkcu3B7NDn3bQy7zDzxXfUQVYzS9t9hk.list_photo.jpg",
        address: "서울 중구 서소문동",
        location: [126.97363348811612, 37.563331828432155],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "샤워실 / 수건 / 대형제빙기 / ️ 무료주차 2시간 30분 / 인바디 측정",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 377000,
          originalPrice: 470000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 6,
        },
        review: {
          rate: 5,
          count: 7,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
      {
        _id: "66431542f1dc21001dca77f5",
        gymName: "왕십리 엘투휘트니스",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18f760b0c1c3e48731/LohhuFQVinkA6XBug2tzEiAwYohuSf2z1D.Big_033.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18f760b0c1c3e48731/2YArM85NTtyqNR4ZAjyZs1SVbQwu6YjXRM2E.Small_033.jpg",
        address: "서울 성동구 상왕십리동",
        location: [127.02383867717424, 37.56915730486325],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️샤워실 / 수건 / ️주차 일 2시간 / ️인바디",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 720000,
          originalPrice: 720000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
      {
        _id: "5f2bb64a100481001c13dfea",
        gymName: "신설 제이휘트니스",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/173c2c0129a1ee3bcd/2fcCgdKTZdEz5X1dfPReh34Fa5Znq2KGiCEH.background_photo.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/173c2c0129a1ee3bcd/LsWmamfaJ4UDCy6mpsYGYVewD6GWW3eZgQ.list_photo.jpg",
        address: "서울 종로구 숭인동",
        location: [127.022846, 37.574035],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "골프"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 2시간 / ️운동복+수건 / ️인바디",
        },
        price: {
          name: "헬스+운동복",
          count: null,
          isLowestPrice: true,
          lowestPrice: 323000,
          originalPrice: 340000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 1,
        },
        review: {
          rate: 5,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
      {
        _id: "65bc7362185776001dbc626d",
        gymName: "혜화 어메이징휘트니스",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18d6822b8bc472a6ed/2WPr6M5f2o7CtvTSkWvWwB2JPkWYSvd2E9Dv.Big__DSC6417.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18d6822b8bc472a6ed/2WiSULC3i9cU3L8xXsMsNAYAU1WpcSP57uQp.Small__DSC6417.jpg",
        address: "서울 종로구 명륜1가",
        location: [126.99694305797325, 37.58631460231251],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복+수건 / ️가입비",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 462000,
          originalPrice: 462000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.93,
          count: 14,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
    ],
    centerList: [
      {
        _id: "6059847543115b00392248e0",
        gymName: "을지로 피트니스101",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1785dad6b2e639542/kXYY4y8ZNcFA177fEscdJ7i7Xc1tjp7wxMvyUTFnxx.jpg",
        address: "서울 중구 저동1가",
        location: [126.98732734452591, 37.565276666657034],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "1:1 P.T 체험권 (2회)",
        },
        service: {
          free: "️주차 (평일: 2시간/주말 4시간 ) / 수건 / Wi-fi / 태닝 / 샐러드바",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 660000,
          originalPrice: 660000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 17,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5faa2611cf2a1a001d936319",
        gymName: "을지로 크로스핏 삼손",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/175b0a4b4fe567e322/2WjeJZnzEMeavHrbhXwVEMwPK76mZMMcitug.list_photo.jpg",
        address: "서울 중구 장교동",
        location: [126.98709621978122, 37.567145281087775],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["크로스핏"],
        program: {
          free: "",
        },
        service: {
          free: "WI-FI / 수건 / 샤워용품 / 인바디",
        },
        price: {
          name: "크로스핏  회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1200000,
          originalPrice: 1200000,
          period: 6,
          priceType: "period",
          itemTags: ["크로스핏"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 14,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "606178dd43115b0039225ae0",
        gymName: "명동 은행회관 헬스클럽",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1787cc020665232fec/4K7pCDmb1Rr5UHrvRJyUA82i4ME2ZEYJMwqnaSxuf384.jpg",
        address: "서울 중구 명동1가",
        location: [126.98544300866244, 37.564987949323516],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "사우나"],
        program: {
          free: "O.T (상시 지도) / G.X수업 (스트레칭 / 요가)",
        },
        service: {
          free: "주차 2시간 / 운동복 / 수건 / Wi-fi / 사우나",
        },
        price: {
          name: "헬스+스파+사우나",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1512000,
          originalPrice: 1512000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스", "사우나"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 38,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "609113c7c70b9e0039948b8a",
        gymName: "동대문 박영길짐앤피티",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17936b541e8252437f/4K7pPeq4QPeQAJJDwV8aXpm34Cqiqohu8fzE8q3mnEfz.jpg",
        address: "서울 종로구 창신동",
        location: [127.01083413334536, 37.572729783255156],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["P.T", "헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / Wi-fi",
        },
        price: {
          name: "헬스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 600000,
          originalPrice: 600000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 3.88,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6088c014c70b9e0039945ad9",
        gymName: "약수 한국체육관 복싱다이어트",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179162e4e9a2af43f9/4K7pPZZWwMYEqwzifeUPJecKsbrg3nMNwpxKWTBq1SVN.jpg",
        address: "서울 중구 신당동",
        location: [127.01209742570951, 37.55690067831976],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 수건 / Wi-fi / 락커",
        },
        price: {
          name: "복싱",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1200000,
          originalPrice: 1200000,
          period: 12,
          priceType: "period",
          itemTags: ["복싱"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "65d3110d5e59db001d7f0d42",
        gymName: "동대문역 짱핏",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18dc07a9bd51ffdac4/MH411keVf3Pq2pQHr2q4784zjrRpmsPeYn.list_photo.jpg",
        address: "서울 종로구 창신동",
        location: [127.01172738010354, 37.57216394855558],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️사물함",
        },
        price: {
          name: "PT 회원권",
          count: 40,
          isLowestPrice: false,
          lowestPrice: 2400000,
          originalPrice: 2400000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6697a1ae01d0e4001dbcc243",
        gymName: "신당 MONDO PT STUDIO",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/190c04f8fb93da26cb/2ZxM8SeHGhDqzve5UVYxHTFS5Lx3pt4Ck3Qm.list_photo.jpg",
        address: "서울 중구 신당동",
        location: [127.01602653005348, 37.56096856870937],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "무료PT 1회",
        },
        service: {
          free: "운동복 수건 / 공용락카 / 주차",
        },
        price: {
          name: "PT 1:1레슨",
          count: 60,
          isLowestPrice: true,
          lowestPrice: 2850000,
          originalPrice: 3000000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: 3,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6177b6126bdf9700390ed152",
        gymName: "신당 관리의기술",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17cbb9f38162dba4d4/4K7xquLTgGDr9WwUDs5Gq2wJqLtkEFFTSnjCC5EmT8DE.jpg",
        address: "서울 중구 흥인동",
        location: [127.01627319106362, 37.5676851838363],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["P.T", "헬스"],
        program: {
          free: "",
        },
        service: {
          free: "주차 / 수건 / Wi-fi",
        },
        price: {
          name: "1:1 P.T (횟수제)",
          count: 30,
          isLowestPrice: false,
          lowestPrice: 1650000,
          originalPrice: 1650000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6321454882a1c2001d14e202",
        gymName: "종로 스포짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18339f6a20fe5f94e/kXjvwH8c7VMy1K45LqKEzxNAyFcnP766Nz36VAyF68.jpg",
        address: "서울 종로구 서린동",
        location: [126.98130878139783, 37.56932942118991],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스", "G.X"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 수건 / 양말 / / 샴푸 / 바디워시 / ️ 주차 2시간 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 480000,
          originalPrice: 480000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.81,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "63bbc28a33db2b001d47b24e",
        gymName: "회현 더코어필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/185956fee3c5831ac4/2WRTMU7LK8bzvsZtTAHKd15ut5N9n6qx3fZT.Small_231128_회현_더코어필라테스_34.jpg",
        address: "서울 중구 회현동1가",
        location: [126.98055017543099, 37.55922913034157],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["기구필라테스", "필라테스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 2시간 가능 / ️수건 / 샤워실 / 락커",
        },
        price: {
          name: "5:1그룹 필라테스 (주 2회)",
          count: 96,
          isLowestPrice: true,
          lowestPrice: 1612800,
          originalPrice: 2000000,
          period: null,
          priceType: "count",
          itemTags: ["필라테스"],
          lowestPriceRemainingCount: 5,
        },
        review: {
          rate: 5,
          count: 2,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "62e913e9f9efad001d8f473e",
        gymName: "을지로 펄스핏 피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1825e75c7082a576a4/4K8gHYEb5rWJtJKJpHwCnL8V5xTn6yNPKGD5LcYzAx9E.jpg",
        address: "서울 중구 을지로1가",
        location: [126.97951563415681, 37.5657386554874],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "유료주차 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 396000,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.93,
          count: 29,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "632d2a6967a7ff001d507f2b",
        gymName: "광화문 이스트 골프라운지",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/183686dadc937bb767/2aFefNkefcTcYBSxbxtQhqGBDgxiDjSERsa6.photo_2.900x676.jpg",
        address: "서울 종로구 종로1가",
        location: [126.97989631253533, 37.57070320710209],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["골프"],
        program: {
          free: "O.T",
        },
        service: {
          free: "주차 2시간",
        },
        price: {
          name: "MEMBERSHIP🏌️‍♂️50min",
          count: null,
          isLowestPrice: false,
          lowestPrice: 3000000,
          originalPrice: 3000000,
          period: 6,
          priceType: "period",
          itemTags: ["골프"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "664d5ee3f1dc21001dcdfde6",
        gymName: "종로 온리스웻짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18f9e3aa83e39150aa/2ZxGPVHsTvz3dJVBCkKSco9gaQBHpiEdnG1W.센터 Small 복사.jpg",
        address: "서울 종로구 숭인동",
        location: [127.01593320600418, 37.57449252765354],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "️무료PT (월 2회)",
        },
        service: {
          free: "️수건 ️1회용 샤워타올 / ️헤어 스프레이 ️퍼퓸 바디 로션 / ️헤어 토닉 ️헤어 젤 / ️1회용 칫솔 ️치약 / ️샴푸 ️린스 ️바디워시 / ️면봉 ️화장솜 / ️공용락커 / ️주차 / - 건물 주차 만차시 불가한 점 양해를 부탁 드립니다.",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 480000,
          originalPrice: 480000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "658a892070ca5e001dcf3f4a",
        gymName: "황학 야무짐 복싱",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18ca527a604aac34f/Q1kRbm2TtwVTrpvQVvCpr1B1qo7n2WcUZ3.센터 Small 복사.jpg",
        address: "서울 중구 황학동",
        location: [127.0224994, 37.5659152],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복, 수건, 개인사물함",
        },
        price: {
          name: "복싱 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 800000,
          originalPrice: 900000,
          period: 6,
          priceType: "period",
          itemTags: ["복싱"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "669dedea01d0e4001dbef127",
        gymName: "신금호 더블와이짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/190d8e95cc24be00bf/2dWHGqauMFZgYXFYivATEgYB7rGJqimtEVi8.1.jpg",
        address: "서울 성동구 금호동2가",
        location: [127.01952210284115, 37.55429165249153],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "회원권 등록 시 PT 2회",
        },
        service: {
          free: "주차 : 2시간 부료 / 샤워 수건 /",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 470440,
          originalPrice: 475200,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 100,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "63d48190ae25d1022c756647",
        gymName: "신금호 팀키스짐 24시",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/185f61a1e0c5a5cf32/2dWHGrnNhztVqYGdTLsZURiuby4A5eCN9gvx.Small__DSC7245.jpg",
        address: "서울 성동구 금호동2가",
        location: [127.01988143166126, 37.5543253799517],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / 샤워실 / Wi-fi",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 600000,
          originalPrice: 600000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 33,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "64422f458ec65b001d34507d",
        gymName: "후암 텐세그리티",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/187a288a71d526ed1f/4K8hKdqZKtdWuf41K5pYKjDPJVCj4uSPSvrJuvqPm7Hz.jpg",
        address: "서울 용산구 후암동",
        location: [126.98349228750746, 37.54886810307899],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "주차 시간제한 없음",
        },
        price: {
          name: "헬스 (+운동복+락커)",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1200000,
          originalPrice: 1200000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6666ab3f6a36af001d864a9b",
        gymName: "혜화 슈퍼스타휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/190010cefa414be71/2ZvGRn1fNRVrMyniZ6LTweRXbyXip88aXC2E.list_photo.jpg",
        address: "서울 종로구 혜화동",
        location: [127.00206620087451, 37.58394501195024],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️수건.샴푸,바디클렌져 / ️기계식 주차 (외제차, 2,000cc 이상 불가)",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 649000,
          originalPrice: 790000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 5,
          count: 14,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "61dd1b6843554f0039f5d308",
        gymName: "왕십리 릴리브짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17e47b311b038879d2/2YBGKWcFXhcd3ii3Y3HYVsr5x9sakLGZW3bG.list_photo.jpg",
        address: "서울 성동구 하왕십리동",
        location: [127.02402841597807, 37.56651532102589],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "OT",
        },
        service: {
          free: "️수건,주차장(자주식 4시간)",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 720000,
          originalPrice: 720000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "62c3eefd99269f001d846287",
        gymName: "시청 요가타운 서소문교육원",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/181cd5d8c511a9b79a/4K8g81Hip8Do9PTbbeREKtTTABr6BLQQD7NtWzShtJc8.jpg",
        address: "서울 중구 서소문동",
        location: [126.9727450920451, 37.56303429786593],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["요가", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "요가복 / 수건",
        },
        price: {
          name: "요가 (주 2회)",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1400000,
          originalPrice: 1400000,
          period: 12,
          priceType: "period",
          itemTags: ["요가"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
    ],
  },
};

export default data;
